jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: dbt_pg_admin
      password: "{{ env_var('DBT_PG_PASSWORD') }}"
      port: 5432
      database: jaffle_shop
      schema: dbt_trial
      # threads: [optional, 1 or more]
      # keepalives_idle: 0 # default 0, indicating the system default. See below
      # connect_timeout: 10 # default 10 seconds
      retries: 1
      # search_path: [optional, override the default postgres search_path]
      # role: [optional, set the role dbt assumes when executing queries]
      # sslmode: [optional, set the sslmode used to connect to the database]
      # sslcert: [optional, set the sslcert to control the certifcate file location]
      # sslkey: [optional, set the sslkey to control the location of the private key]
      # sslrootcert: [optional, set the sslrootcert config value to a new file path in order to customize the file location that contain root certificates]